apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: <CONTAINER_REGISTRY_URL>/<IMAGE_NAME>:latest
        ports:
        - containerPort: 8501
